@yarp = https://localhost:8000
@backend1 = https://localhost:9000
@backend2 = https://localhost:9100

GET {{yarp}}/hello
Accept: application/json

###

GET {{backend1}}/weatherforecast
Accept: application/json

